1.To perform the operations on a 1D array of the first 10 positive integers, we can use the NumPy library in Python. Here's the step-by-step process:

Create a 1D array of the first 10 positive integers.
Print the array.
Find the sum of all elements in the array.
Calculate the mean of the elements.

In [7]:
import numpy as np

# Create a 1D array of the first 10 positive integers
array = np.arange(1, 11)

# Print the array
print("Array:", array)

# Find the sum of all elements in the array
array_sum = np.sum(array)
print("Sum of all elements:", array_sum)

# Calculate the mean of the elements
array_mean = np.mean(array)
print("Mean of elements:", array_mean)


Array: [ 1  2  3  4  5  6  7  8  9 10]
Sum of all elements: 55
Mean of elements: 5.5


## 2Create a 2D array of shape (3, 4) with random integers between 1 and 10.
Print the array.
Find the maximum and minimum values in the array.
Calculate the sum of each row and each column.

In [9]:
import numpy as np

# Create a 2D array of shape (3, 4) with random integers between 1 and 10
array_2d = np.random.randint(1, 11, size=(3, 4))

# Print the array
print("2D Array:\n", array_2d)

# Find the maximum and minimum values in the array
max_value = np.max(array_2d)
min_value = np.min(array_2d)
print("Maximum value:", max_value)
print("Minimum value:", min_value)

# Calculate the sum of each row and each column
row_sums = np.sum(array_2d, axis=1)
column_sums = np.sum(array_2d, axis=0)
print("Sum of each row:", row_sums)
print("Sum of each column:", column_sums)


2D Array:
 [[10  6  9  6]
 [ 2  7  5  6]
 [ 5  9  9  2]]
Maximum value: 10
Minimum value: 2
Sum of each row: [31 20 25]
Sum of each column: [17 22 23 14]


### **3.Create a 1D array of 20 random integers between 1 and 100.**
   - Print the array.
   - Print the elements from index 5 to 15.
   - Print every second element of the array.

In [10]:
import numpy as np

# Create a 1D array of 20 random integers between 1 and 100
array_1d = np.random.randint(1, 101, size=20)

# Print the array
print("1D Array:", array_1d)

# Print the elements from index 5 to 15
print("Elements from index 5 to 15:", array_1d[5:16])

# Print every second element of the array
print("Every second element:", array_1d[::2])


1D Array: [85  4 79 58 46 80 41 96 70 32 96 12 48 21 97 82  6 58  1 18]
Elements from index 5 to 15: [80 41 96 70 32 96 12 48 21 97 82]
Every second element: [85 79 46 41 70 96 48 97  6  1]


4. **Create a 2D array of shape (5, 5) with random integers between 1 and 50.**
   - Print the array.
   - Extract and print the second row.
   - Extract and print the third column.
   - Extract and print a 3x3 subarray from the original array.

In [11]:
import numpy as np

# Create a 2D array of shape (5, 5) with random integers between 1 and 50
array_2d = np.random.randint(1, 51, size=(5, 5))

# Print the array
print("2D Array:\n", array_2d)

# Extract and print the second row
second_row = array_2d[1, :]
print("Second Row:", second_row)

# Extract and print the third column
third_column = array_2d[:, 2]
print("Third Column:", third_column)

# Extract and print a 3x3 subarray from the original array
subarray_3x3 = array_2d[1:4, 1:4]
print("3x3 Subarray:\n", subarray_3x3)


2D Array:
 [[34 32 31 17 34]
 [37  8 49  4 15]
 [43 15 42  7 14]
 [24 44 50 14 15]
 [20 34 18 50 19]]
Second Row: [37  8 49  4 15]
Third Column: [31 49 42 50 18]
3x3 Subarray:
 [[ 8 49  4]
 [15 42  7]
 [44 50 14]]


5. **Create two 1D arrays of 10 random integers each.**
   - Concatenate the two arrays.
   - Sort the concatenated array.
   - Find the unique elements in the concatenated array.

In [12]:
import numpy as np

# Create two 1D arrays of 10 random integers each
array1 = np.random.randint(1, 101, size=10)
array2 = np.random.randint(1, 101, size=10)

# Print the arrays
print("Array 1:", array1)
print("Array 2:", array2)

# Concatenate the two arrays
concatenated_array = np.concatenate((array1, array2))
print("Concatenated Array:", concatenated_array)

# Sort the concatenated array
sorted_array = np.sort(concatenated_array)
print("Sorted Array:", sorted_array)

# Find the unique elements in the concatenated array
unique_elements = np.unique(concatenated_array)
print("Unique Elements:", unique_elements)


Array 1: [87 24 97 78 26 40 53 82 21 59]
Array 2: [36 76 66 48 48 77 93 77 18 66]
Concatenated Array: [87 24 97 78 26 40 53 82 21 59 36 76 66 48 48 77 93 77 18 66]
Sorted Array: [18 21 24 26 36 40 48 48 53 59 66 66 76 77 77 78 82 87 93 97]
Unique Elements: [18 21 24 26 36 40 48 53 59 66 76 77 78 82 87 93 97]


6. **Create a 2D array of shape (4, 4) with random integers between 1 and 20.**
   - Print the array.
   - Flatten the array into a 1D array.
   - Reshape the flattened array back into a 2D array of shape (2, 8).

In [13]:
import numpy as np

# Create a 2D array of shape (4, 4) with random integers between 1 and 20
array_2d = np.random.randint(1, 21, size=(4, 4))

# Print the array
print("2D Array:\n", array_2d)

# Flatten the array into a 1D array
flattened_array = array_2d.flatten()
print("Flattened Array:", flattened_array)

# Reshape the flattened array back into a 2D array of shape (2, 8)
reshaped_array = flattened_array.reshape((2, 8))
print("Reshaped Array (2x8):\n", reshaped_array)


2D Array:
 [[ 8  5 18 11]
 [13 11 14  3]
 [15 15 17  8]
 [ 1  9  3 10]]
Flattened Array: [ 8  5 18 11 13 11 14  3 15 15 17  8  1  9  3 10]
Reshaped Array (2x8):
 [[ 8  5 18 11 13 11 14  3]
 [15 15 17  8  1  9  3 10]]


7. **Create a 1D array of 15 random integers between 1 and 50.**
   - Print the array.
   - Calculate and print the standard deviation of the array.
   - Find and print the index of the maximum value in the array.
   - Normalize the array (scale the values to a range between 0 and 1).

7. **Create a 1D array of 15 random integers between 1 and 50.**
   - Print the array.
   - Calculate and print the standard deviation of the array.
   - Find and print the index of the maximum value in the array.
   - Normalize the array (scale the values to a range between 0 and 1).

In [15]:
import numpy as np

# Create a 1D array of 15 random integers between 1 and 50
array_1d = np.random.randint(1, 51, size=15)

# Print the array
print("1D Array:", array_1d)

# Calculate and print the standard deviation of the array
std_dev = np.std(array_1d)
print("Standard Deviation:", std_dev)

# Find and print the index of the maximum value in the array
max_index = np.argmax(array_1d)
print("Index of Maximum Value:", max_index)

# Normalize the array (scale the values to a range between 0 and 1)
normalized_array = (array_1d - np.min(array_1d)) / (np.max(array_1d) - np.min(array_1d))
print("Normalized Array:", normalized_array)


1D Array: [32 49 45 23 18 15 24 32 32 34 34 39  1 10 41]
Standard Deviation: 12.903746226064222
Index of Maximum Value: 1
Normalized Array: [0.64583333 1.         0.91666667 0.45833333 0.35416667 0.29166667
 0.47916667 0.64583333 0.64583333 0.6875     0.6875     0.79166667
 0.         0.1875     0.83333333]


8. **Create two 2D arrays of shape (3, 3) with random integers between 1 and 10.**
   - Print both arrays.
   - Perform element-wise addition, subtraction, and multiplication of the arrays.
   - Calculate the dot product of the arrays.

In [16]:
import numpy as np

# Create two 2D arrays of shape (3, 3) with random integers between 1 and 10
array1 = np.random.randint(1, 11, size=(3, 3))
array2 = np.random.randint(1, 11, size=(3, 3))

# Print both arrays
print("Array 1:\n", array1)
print("Array 2:\n", array2)

# Perform element-wise addition, subtraction, and multiplication of the arrays
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2

print("Element-wise Addition:\n", addition)
print("Element-wise Subtraction:\n", subtraction)
print("Element-wise Multiplication:\n", multiplication)

# Calculate the dot product of the arrays
dot_product = np.dot(array1, array2)
print("Dot Product:\n", dot_product)


Array 1:
 [[ 8  5  7]
 [10 10  9]
 [ 7  5  2]]
Array 2:
 [[ 9  3  3]
 [ 7 10  9]
 [ 4  5  3]]
Element-wise Addition:
 [[17  8 10]
 [17 20 18]
 [11 10  5]]
Element-wise Subtraction:
 [[-1  2  4]
 [ 3  0  0]
 [ 3  0 -1]]
Element-wise Multiplication:
 [[ 72  15  21]
 [ 70 100  81]
 [ 28  25   6]]
Dot Product:
 [[135 109  90]
 [196 175 147]
 [106  81  72]]
